### ISSUE TITLE
Invalid XML in system.xml

### ISSUE THREAD

**Issue by mikehenze** [k3live/magento2-woopra#2]
Throws errors in developer mode, please check.

**Comment by kmcgregor** [comment]
mikehenze,
Can you please share your development environment details, Magento version, and the error you are receiving?

**Comment by mikehenze** [comment]
Byte Hypernode with redis
Magento 2.1.7

Error:
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid XML in file /data/web/magento2/vendor/woopra/analytics-m2/etc/adminhtml/system.xml:
Element 'group', attribute 'expanded': The attribute 'expanded' is not allowed.
Line: 21

Element 'group', attribute 'expanded': The attribute 'expanded' is not allowed.
Line: 41

Element 'field', attribute 'validate': The attribute 'validate' is not allowed.
Line: 49

Element 'field', attribute 'validate': The attribute 'validate' is not allowed.
Line: 62

Element 'field', attribute 'validate': The attribute 'validate' is not allowed.
Line: 93

Element 'field', attribute 'validate': The attribute 'validate' is not allowed.
Line: 106

Element 'field', attribute 'validate': The attribute 'validate' is not allowed.
Line: 119

Element 'group', attribute 'expanded': The attribute 'expanded' is not allowed.
Line: 140

Element 'group', attribute 'expanded': The attribute 'expanded' is not allowed.
Line: 222

**Comment by kmcgregor** [comment]
Invalid XML removed from etc/adminhtml/system.xml
