### ISSUE TITLE
Breaks checkout when Woopra is down

### ISSUE THREAD

**Issue by mikehenze** [k3live/magento2-woopra#4]
When the Woopra service is down it breaks the checkout.
Please build in a safeguard for this.

**Comment by kmcgregor** [comment]
Unable to reproduce in test environment. Can you better describe what is happening during checkout? For testing the domain was changed in script.phtml.

**Comment by mikehenze** [comment]
Checkout did not load when the woopra service was down.
Was only fixed by removing the plugin.
