### ISSUE TITLE
Error on search results

### ISSUE THREAD

**Issue by mikehenze** [k3live/magento2-woopra#5]
Magento 2.1.9

Keep getting this error for some users:

Notice: Undefined index: q in /data/web/magento2/vendor/woopra/analytics-m2/Observer/Observer.php on line 178

Trace:
#0 /data/web/magento2/vendor/woopra/analytics-m2/Observer/Observer.php(178): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/data/web/magen...', 178, Array)
#1 /data/web/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Woopra\Analytics\Observer\Observer->execute(Object(Magento\Framework\Event\Observer))
#2 /data/web/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Woopra\Analytics\Observer\Observer), Object(Magento\Framework\Event\Observer))
#3 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#4 /data/web/magento2/var/generation/Magento/Framework/Event/Invoker/InvokerDefault/Interceptor.php(26): Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->___callPlugins('dispatch', Array, Array)
#5 /data/web/magento2/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->dispatch(Array, Object(Magento\Framework\Event\Observer))
#6 /data/web/magento2/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('controller_acti...', Array)
#7 /data/web/magento2/vendor/magento/framework/App/Action/Action.php(91): Magento\Framework\Event\Manager\Proxy->dispatch('controller_acti...', Array)
#8 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Amasty\Shopby\Controller\Search\Result\Index\Interceptor->___callParent('dispatch', Array)
#10 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Amasty\\Shopby\\C...', 'dispatch', Object(Amasty\Shopby\Controller\Search\Result\Index\Interceptor), Array, 'contextPlugin')
#11 /data/web/magento2/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Amasty\Shopby\Controller\Search\Result\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Amasty\\Shopby\\C...', 'dispatch', Object(Amasty\Shopby\Controller\Search\Result\Index\Interceptor), Array, 'customer-app-ac...')
#14 /data/web/magento2/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Amasty\Shopby\Controller\Search\Result\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Amasty\\Shopby\\C...', 'dispatch', Object(Amasty\Shopby\Controller\Search\Result\Index\Interceptor), Array, 'storeCheck')
#17 /data/web/magento2/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Amasty\Shopby\Controller\Search\Result\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Amasty\\Shopby\\C...', 'dispatch', Object(Amasty\Shopby\Controller\Search\Result\Index\Interceptor), Array, 'weee-app-action...')
#20 /data/web/magento2/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Amasty\Shopby\Controller\Search\Result\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Amasty\\Shopby\\C...', 'dispatch', Object(Amasty\Shopby\Controller\Search\Result\Index\Interceptor), Array, 'tax-app-action-...')
#23 /data/web/magento2/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Amasty\Shopby\Controller\Search\Result\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Amasty\Shopby\Controller\Search\Result\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /data/web/magento2/var/generation/Amasty/Shopby/Controller/Search/Result/Index/Interceptor.php(39): Amasty\Shopby\Controller\Search\Result\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#26 /data/web/magento2/vendor/magento/framework/App/FrontController.php(55): Amasty\Shopby\Controller\Search\Result\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#28 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#29 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#30 /data/web/magento2/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#33 /data/web/magento2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#36 /data/web/magento2/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#37 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#38 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#39 /data/web/magento2/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#40 /data/web/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#41 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'Amasty_Invisibl...')
#42 /data/web/magento2/app/code/Amasty/InvisibleCaptcha/Plugin/Predispatch.php(77): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#43 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Amasty\InvisibleCaptcha\Plugin\Predispatch->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#44 /data/web/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#45 /data/web/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#46 /data/web/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#47 /data/web/magento2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#48 {main}

**Comment by kmcgregor** [comment]
Try updating line 174 to read: if ($request['q']) {
Can you force this error?
Are you running any extensions that modify the default search behavior?

**Comment by mikehenze** [comment]
I changed the line (175 actually).
I will let you know if it happens again.

I cannot force the error.
Only some users get this error.

We sent out a mailchimp campaign with links pointing to search results.
We use Mageworx Search Suite extension which comes bundled with the Codazon Fastest theme

**Comment by mikehenze** [comment]
Now i get this:

Notice: Undefined index: q in /data/web/magento2/vendor/woopra/analytics-m2/Observer/Observer.php on line 175

**Comment by mikehenze** [comment]
Also breaks on change password:

Notice: Undefined index: change_password in /data/web/magento2/vendor/woopra/analytics-m2/Observer/Observer.php on line 268
